# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.3
_src_path: git@github.com:dribia/dritemplate-blank.git
client_name: Dribia Data Research
license:
    authorized: "[\n    \"bsd\",\n    \"new bsd\",\n    \"bsd license\",\n    \"0BSD\"\
        ,\n    \"Zero-Clause BSD (0BSD)\",\n    \"3-Clause BSD\",\n    \"BSD-3-Clause\"\
        ,\n    \"BSD 3-Clause\",\n    \"BSD 3\",\n    \"BSD 2-Clause\",\n    \"BSD-2-Clause\"\
        ,\n    \"Apache-2.0 AND BSD-2-Clause\",\n    \"Apache-2.0 AND MIT\",\n   \
        \ \"apache 2\",\n    \"apache\",\n    \"Apache Software\",\n    \"Apache-1.0\"\
        ,\n    \"Apache-1.1\",\n    \"Apache-2.0\",\n    \"Apache 2.0\",\n    \"Apache\
        \ License 2.0\",\n    \"Apache License v2.0\",\n    \"Apache License, Version\
        \ 2.0\",\n    \"MIT\",\n    \"MIT AND BSD-3-Clause\",\n    \"MIT-CMU\",\n\
        \    \"CMU License (MIT-CMU)\",\n    \"MIT No Attribution License (MIT-0)\"\
        ,\n    \"Python Software Foundation\",\n    \"PSF-2.0\",\n    \"ISC\",\n \
        \   \"ISC License (ISCL)\",\n    \"historical permission notice and disclaimer\
        \ (hpnd)\",\n    \"MPL-2.0\",\n    \"Mozilla Public License 2.0 (MPL 2.0)\"\
        ,\n    \"Artistic\",\n    \"The Unlicense (Unlicense)\",\n]"
    unauthorized: "[\n    \"gpl v3\",\n    \"GPL-3.0-or-later\",\n    \"AGPL-3.0-or-later\"\
        ,\n    \"AGPL\",\n    \"MPL-1.0\",\n    \"MPL-1.1\",\n    \"LGPL\",\n    \"\
        LGPL-3.0-or-later\",\n]"
license_option: dribia-ip
license_year: '2025'
project_description: GitHub configurations for Dribia organization.
project_email: code@dribia.com
project_name: Github
project_suffix: -config
python_version: '3.13'
