name: " Data exploration"
description: "Explora les dades"
title: ":monocle_face: "
type: "Data Exploration"
assignees: []

body:

- type: textarea
  id: data
  attributes:
    label: Data a explorar
    description: "Indica quina taula, dataframe o conjunt concret de dades cal analitzar. Limita b茅 labast per evitar dispersi贸."
  validations:
    required: true

- type: textarea
  id: objectiu
  attributes:
    label: Objectiu
    description: "escriu qu猫 vols aprendre a partir de les dades: Quines preguntes vols respondre? Quina relaci贸, patr贸 o m猫trica vols comprovar?"
  validations:
    required: false

- type: textarea
  id: output
  attributes:
    label: Output esperat
    description: "Defineix clarament qu猫 esperes obtenir de lexploraci贸."
    placeholder: |
      - [ ] Un resum escrit de conclusions.
      - [ ] Un grfic concret (ex: evoluci贸 trimestral, distribuci贸 de valors...).
      - [ ] Una taula comparativa (X vs Y).
      - [ ] Una diapositiva per lEoS.
  validations:
    required: false
