name: "👔 No code"
description: "Tasques que no impliquen codi"
title: ":necktie: "
type: "No code"
assignees: []

body:

- type: textarea
  id: context
  attributes:
    label: Context
    description: "D'on sorgeix la necessitat? Qui ho ha demanat? Quin ús tindrà més endavant?"
  validations:
    required: false

- type: textarea
  id: objectiu
  attributes:
    label: Objectiu
    description: "Què has de poder fer després d’acabar la tasca que ara no pots fer?"
  validations:
    required: false

- type: textarea
  id: tasques
  attributes:
    label: Tasques
    description: "Utilitza aquesta secció per desglossar la tasca en parts més petites i manejables."
    placeholder: |
      - [ ] Descripció de la primera tasca.
      - [ ] Descripció de la segona tasca.
      - [ ] Descripció de la tercera tasca.
  validations:
    required: false
