name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  call-test:
    uses: dribia/driworkflows-test/.github/workflows/test.yml@v3
    with:
      repo-name: ${{ github.event.repository.name }}
      generate-badge: false
